---
image:
  name: docker/compose:1.23.2
  entrypoint: ["/bin/sh", "-c"]

variables:
  COMPOSE_FILE: 'docker-compose.test.yml'
  # Required for gitlab public runners
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/

services:
  # Required for gitlab public runners
  - docker:dind

stages:
  - build
  - test

test:
  stage: test
  before_script:
    - docker version
    - docker info
    - docker-compose version
  # TODO: Possibly look into adding something like GNU Parallel
  # to speed things up if more testing is added
  script:
    - docker-compose build --pull --parallel --compress
    - docker-compose run --name build-${CI_JOB_ID} -T --rm sanctum ls -lart -hu
    - docker-compose run --name rspec-${CI_JOB_ID} -T --rm sanctum bundle exec rspec
    - docker-compose run --name rubocop-${CI_JOB_ID} -T --rm sanctum bundle exec rubocop
  # Was hoping to use a cleanup stage, but see
  # https://gitlab.com/gitlab-org/gitlab-runner/issues/1099
  # and https://gitlab.com/gitlab-org/gitlab-runner/issues/1099
  after_script:
    - docker-compose down --remove-orphans --volumes
  tags:
    - docker
