---
image:
  name: docker/compose:1.23.2
  entrypoint: ["/bin/sh", "-c"]

stages:
  - test

before_script:
  - docker version
  - docker-compose version

testing:
  stage: test
  script:
    - docker-compose build
    - docker-compose run --rm sanctum bundle exec rspec
