---
image:
  name: docker/compose:1.23.2
  entrypoint: ["/bin/sh", "-c"]

variables:
  COMPOSE_FILE: 'docker-compose.test.yml'
  COMPOSE_PROJECT_NAME: sanctum-testing-$(head -200 /dev/urandom | cksum | cut -f1 -d " ")

stages:
  - test
  - cleanup

before_script:
  - docker version
  - docker info
  - docker-compose version

testing:
  stage: test
  script:
    - docker-compose build --pull --parallel --compress
    - docker-compose run --name ${CI_JOB_ID} -T --rm sanctum ls -lart -hu
    - docker-compose run --name ${CI_JOB_ID} -T --rm sanctum bundle exec rspec
  after_script:
    - docker-compose down --remove-orphans --volumes

cleanup_job:
  stage: cleanup
  script: docker-compose down --remove-orphans --volumes
  allow_failure: true
  when: always
