---
image: docker:stable

stages:
  - test

variables:
  # Docker inception (docker inside docker)
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - apk add --no-cache python python-dev py-pip build-base \
    libffi libffi-dev openssl openssl-dev linux-headers
  - pip install pip setuptools --upgrade
  - hash pip
  - pip install docker-compose --upgrade
  - docker info

testing:
  stage: test
  tags:
    - docker
  script:
    - docker -v
    - docker-compose build
    - docker-compose run --rm sanctum bundle exec rspec
