---
include:
  - template: Dependency-Scanning.gitlab-ci.yml

stages:
  - test
  - cleanup

testing:
  image:
    name: docker/compose:1.26.0
    entrypoint: ["/bin/sh", "-c"]
  variables:
    COMPOSE_FILE: 'docker-compose.test.yml'
    # Required for gitlab public runners
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/
  services:
    # Required for gitlab public runners
    - docker:dind
  stage: test
  before_script:
    - docker version
    - docker info
    - docker-compose version
  script:
    - docker-compose build --pull --parallel --compress
    - docker-compose run --name ${CI_JOB_ID} -T --rm sanctum ls -lart -hu
    - docker-compose run --name ${CI_JOB_ID} -T --rm sanctum bundle exec rspec
  # Was hoping to use a cleanup stage, but see
  # https://gitlab.com/gitlab-org/gitlab-runner/issues/1099
  # and https://gitlab.com/gitlab-org/gitlab-runner/issues/1099
  after_script:
    - docker-compose down --remove-orphans --volumes
  tags:
    - docker
