---
require:
  - rubocop-rspec
  - rubocop-performance

Rails:
  Enabled: false

AllCops:
  DefaultFormatter: progress
  DisplayCopNames: true
  Exclude: []
  CacheRootDirectory: cache/
  TargetRubyVersion: 2.5

Bundler/OrderedGems:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

RSpec/ExampleLength:
  Max: 25

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingUnderscoreVariable:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 25
